### PR TITLE
Fix all remaining issues

### LINKED ISSUE #2: Support batch ops
https://ipinfo.io/developers/batch

Take into account use cases like https://github.com/ipinfo/python/issues/35 to ensure batch ops support is scalable & robust.

### LINKED ISSUE #25: Remove axios; use normal nodejs HTTP client facility
For some reason the library is using a third party HTTP client. This is unnecessary as we can just use Node.js's native client without adding on another dependency for the user.

### LINKED ISSUE #34: Use versioned cache key
Make sure the cache key contains a number to indicate the version of the cached data. Data changes that change what's expected in cached data require a version change.

### LINKED ISSUE #35: Map integration
Create a simple function that accepts an IP list (max 500k) and returns the JSON response from `https://ipinfo.io/map`.

### PR DESCRIPTION
**Pull request by UmanShahzad**
Fixes #25
Fixes #2 
Fixes #34 
Fixes #35

### CODE REVIEW

**Comment by UmanShahzad** [comment]
TODO: version bump & changelog.

**Review by Treefogg — COMMENTED** [review]
It seems to work wonders

**Comment by UmanShahzad** [comment]
Happy you feel that way @Treefogg !

**Comment by Treefogg** [comment]
I think this will be right on

**Review by Treefogg — COMMENTED** [review]
Yes   Thankyou

**Comment by Treefogg** [comment]
I don't know how it's getting threw

**Review by Treefogg — COMMENTED** [review]
Yesss

**Pull request merged**
